"""add token id in user model.

Revision ID: 81ff36a3fe90
Revises: 562317ab3c3f
Create Date: 2026-03-03 16:25:16.405001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ff36a3fe90'
down_revision: Union[str, Sequence[str], None] = '562317ab3c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('refresh_token_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_id')
    op.drop_column('users', 'access_token_id')
    # ### end Alembic commands ###
